server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/heima?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Woshij8dan!
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 122.112.168.7
    port: 5672
    username: root
    password: Woshij8dan!
    virtual-host: /
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.itcast.hotel.pojo